NVIDIA: SAUCE: Fix redefined kvm_arch_has_irq_bypass()
BugLink: https://bugs.launchpad.net/bugs/2122432

Fix the following kernel build error:

arch/arm64/kvm/arm.c:2718:6: error: redefinition of ‘kvm_arch_has_irq_bypass’
 2718 | bool kvm_arch_has_irq_bypass(void)
      |      ^~~~~~~~~~~~~~~~~~~~~~~
In file included from ./include/linux/kvm_host.h:45,
                 from arch/arm64/kvm/arm.c:12:
./arch/arm64/include/asm/kvm_host.h:1550:20: note: previous definition of ‘kvm_arch_has_irq_bypass’ with type ‘bool(void)’ {aka ‘_Bool(void)’}
 1550 | static inline bool kvm_arch_has_irq_bypass(void)
      |                    ^~~~~~~~~~~~~~~~~~~~~~~

Fixes: 4f60c8032f2f5bfb ("NVIDIA: SAUCE: untested: KVM: arm64: Force guest EL1 to use user-space's partid configuration")

Signed-off-by: Fenghua Yu <fenghuay@nvidia.com>
Acked-by: Matt Ochs <mochs@nvidia.com>
Acked-by: Carol L Soto <csoto@nvidia.com>
Acked-by: Jacob Martin <jacob.martin@canonical.com>
Acked-by: Abdur Rahman <abdur.rahman@canonical.com>
Acked-by: Koba Ko <kobak@nvidia.com>
Signed-off-by: Brad Figg <bfigg@nvidia.com>